---
- name: "update dependencies"
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]

- name: "Add docker gpg Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: "Add Docker Repo"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present


- name: Update apt and install docker-ce
  apt:
    name: [docker-ce, python3-pip]
    state: latest
    update_cache: true

- name: "install Docker dependencies"
  apt: 
    name: [docker-ce-cli, containerd.io]
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: change docker file mode
  become: true
  become_method: sudo
  command: chmod 744 /var/run/docker.sock 

- name: Start Docker service
  systemd: 
    name: docker
    enabled: yes
    state: restarted 

- name: Download minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: ~/minikube-linux-amd64

- name: change permissions minikube
  ansible.builtin.file:
    path: ~/minikube-linux-amd64
    mode: 744

- name: Move minikube file
  become: true
  become_method: sudo
  command: mv ~/minikube-linux-amd64 /usr/local/bin/minikube

- name: Comfirm install of Minikube
  command: minikube version

- name: Download kubectl
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.26.2/bin/linux/amd64/kubectl
    dest: ~/kubectl

- name: change permissions kubectl
  ansible.builtin.file:
    path: ~/kubectl
    mode: 744

- name: Move kubectl file
  become: true
  become_method: sudo
  command: mv ~/kubectl /usr/local/bin/kubectl

- name: minikube start
  become: true
  become_method: sudo
  command: minikube start --force

- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - python
    - unzip

- name: Download the awscli bundle.
  get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/awscli-bundle
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  shell: python /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
  args:
    creates: /usr/bin/aws
  when: aws_cli_unarchive_installer.changed

