---

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: ./site-content/
  with_fileglob:
    - "~/project/site-content/*"
  tags:
    - site-content

- name: copy other files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: "~/project/Dockerfile", dest: "./Dockerfile" }
    - { src: "~/project/run_docker.sh", dest: "./run_docker.sh" }
    - { src: "~/project/run_kubernetes.sh", dest: "./run_kubernetes.sh" }
    - { src: "~/project/upload_docker.sh", dest: "./upload_docker.sh" }
    - { src: "~/project/green-ansible.yml", dest: "./green-ansible.yml" }
  tags:
    - req files

- name: aws configure changes
  shell: |
    aws configure set aws_access_key_id {{ lookup('env', 'AWS_ACCESS_KEY_ID')}} --profile circleci
    aws configure set aws_secret_access_key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}} --profile circleci
    aws configure set region us-east-1 --profile circleci

- name: aws eks connect
  shell: |
    export AWS_CONFIG_FILE=~/.aws/config
    export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
    export AWS_PROFILE=circleci
    AWS_PROFILE=circleci aws eks --region us-east-1 update-kubeconfig --name udacity-cluster
    # kubectl config use-context arn:aws:eks:us-east-1:617136264054:cluster/udacity-cluster
    # kubectl config set-context --current --namespace udacity
    # kubectl get pods -n udacity



