---

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: ./site-content/
  with_fileglob:
    - "~/project/site-content/*"
  tags:
    - site-content

- name: copy other files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: "~/project/Dockerfile", dest: "./Dockerfile" }
    - { src: "~/project/run_docker.sh", dest: "./run_docker.sh" }
    - { src: "~/project/run_kubernetes.sh", dest: "./run_kubernetes.sh" }
    - { src: "~/project/upload_docker.sh", dest: "./upload_docker.sh" }
    - { src: "~/project/green-ansible.yml", dest: "./green-ansible.yml" }
  tags:
    - req files

# - name: aws configure changes
#   shell: |
#     aws configure set aws_access_key_id {{ lookup('env', 'AWS_ACCESS_KEY_ID')}} --profile udacity
#     aws configure set aws_secret_access_key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}} --profile udacity
#     aws configure set region us-east-1 --profile udacity

# - name: aws eks connect
#   shell: |
#     export AWS_CONFIG_FILE=~/.aws/config
#     export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
#     export AWS_PROFILE=udacity
#     aws s3 ls

- name: Build docker image 
  docker_image:
    build:
      path: .
      pull: no
    name: riccardopixel/nginx
    tag: "{{ image_tag }}"
    source: build
  tags:
    - build

- name: Start docker container
  docker_container:
    name: nginx-docker
    image: riccardopixel/nginx:{{ image_tag }}
    ports:
     - "8000:80"
    detach: yes
    state: started
  tags:
    - start

